# Generated by Django 6.1.1 on 2026-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='students.university')),
            ],
        ),
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='meals.meal')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_services', to='students.university')),
            ],
            options={
                'ordering': ['-service_date', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='MealToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='meals.mealservice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_tokens', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Success'), ('already_redeemed', 'Already Redeemed'), ('invalid_card', 'Invalid Card'), ('blocked_card', 'Blocked Card'), ('expired_card', 'Expired Card'), ('invalid_token', 'Invalid Token'), ('expired_token', 'Expired Token'), ('token_not_assigned', 'Token Not Assigned To Student'), ('invalid_meal', 'Invalid Meal'), ('inactive_student', 'Inactive Student'), ('wrong_university', 'Wrong University'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('meal_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='students.mealcard')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_scan_logs', to=settings.AUTH_USER_MODEL)),
                ('meal_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='meals.mealservice')),
                ('meal_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='meals.mealtoken')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='MealRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('rejected', 'Rejected')], default='success', max_length=20)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('meal_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='students.mealcard')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_redemptions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_redemptions', to='students.student')),
                ('meal_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='meals.mealservice')),
                ('meal_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='meals.mealtoken')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealservice',
            constraint=models.UniqueConstraint(fields=('meal', 'university', 'service_date'), name='unique_meal_service_per_university_day'),
        ),
        migrations.AddConstraint(
            model_name='mealtoken',
            constraint=models.UniqueConstraint(fields=('meal_service', 'student'), name='one_token_per_student_per_meal_service'),
        ),
        migrations.AddConstraint(
            model_name='mealredemption',
            constraint=models.UniqueConstraint(fields=('student', 'meal_service'), name='one_redemption_per_student_per_service'),
        ),
        migrations.AddConstraint(
            model_name='mealredemption',
            constraint=models.UniqueConstraint(fields=('meal_token',), name='one_redemption_per_meal_token'),
        ),
    ]
