"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
"""SECRET_KEY = 'django-insecure-rqwv=7tk-lt+z-2rzx9h_4t&#$v88veef288dn#zpq!@%&db!a' """
SECRET_KEY = os.environ.get("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "students",
    "meals",
    "kitchen",
   
    "reports",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600
    )
} 

AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/




# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


JAZZMIN_SETTINGS = {
    "site_title": "SmartMeal Admin",
    "site_header": "SmartMeal",
    "site_brand": "SmartMeal",
    "welcome_sign": "Welcome to SmartMeal",

    "show_sidebar": True,
    "navigation_expanded": True,

    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "/admin/",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "QR Scanner",
            "url": "/kitchen/qr-scanner/",
            "icon": "fas fa-qrcode",
        },
            {
            "name": "QR Scanner2",
            "url": "/meals/scanner/",
            "icon": "fas fa-qrcode",
        },
    ],

    "icons": {
        "accounts": "fas fa-users",
        "students": "fas fa-user-graduate",
        "meals": "fas fa-utensils",
        "kitchen": "fas fa-kitchen-set",
        "reports": "fas fa-chart-bar",
    },
}




# Static files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

from celery.schedules import crontab

LOGIN_URL = "accounts:login"
LOGOUT_REDIRECT_URL = "accounts:login"
# settings.py

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Kampala"

USE_I18N = True

USE_TZ = True


CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

CELERY_TIMEZONE = "Africa/Kampala"

CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {


"generate-lunch-tokens-every-day": {
    "task": "meals.tasks.generate_lunch_tokens",
    "schedule": crontab(
        hour=12,
        minute=30,
    ),
},

"generate-saapa-tokens-every-day": {
    "task": "meals.tasks.generate_saapa_tokens",
    "schedule": crontab(
        hour=18,
        minute=30,
    ),
},


}
